[versions] # also check project root build.gradle.kts for versions
androidx-animation = "1.5.0-beta03"
androidx-foundation = "1.5.0-beta03"
androidx-appcompat = "1.6.1"
androidx-coreKtx = "1.10.1"
androidxActivityVer = "1.7.2"
androidGradlePlugin = "8.1.0"
junit = "4.13.2"
junit-junitJupiterApi = "5.8.2"
junit-junitJupiterEngine = "5.8.2"
junitJupiterEngine = "5.8.2"
junitJupiterApi = "5.8.2"
kotlin = "1.9.0"
kotlinxCoroutinesCore = "1.7.3"
lifecycleRuntimeKtx = "2.6.1"
material = "1.5.0-beta03"
moleculeRuntime = "0.9.0"
savedstateKtx = "1.2.1"
spotless = "6.7.0"
jetbrainsComposePlugin = "1.5.0-beta01"
skiko = "0.7.72"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivityVer" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidx-coreKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "material" }
androidx-savedstate-ktx = { module = "androidx.savedstate:savedstate-ktx", version.ref = "savedstateKtx" }
animation = { module = "androidx.compose.animation:animation", version.ref = "androidx-animation" }
foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-foundation" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-jupiter-api-v580 = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-junitJupiterApi" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiterEngine" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiterApi" }
junit-jupiter-engine-v582 = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-junitJupiterEngine" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesCore" }
molecule-runtime = { module = "app.cash.molecule:molecule-runtime", version.ref = "moleculeRuntime" }
skiko = { module = "org.jetbrains.skiko:skiko", version.ref = "skiko" }
skiko-js = { module = "org.jetbrains.skiko:skiko-js-wasm-runtime", version.ref = "skiko" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrainsComposePlugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
