name: CI Assemble, Test, and Publish

on:
  workflow_call:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Apply Signing
      if: ${{ github.event_name != 'pull_request' }}
      env:
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      run: ./.github/apply_signing.sh

    - name: Assemble
      run: ./gradlew assemble --stacktrace

    - name: Testing
      run: ./gradlew check --stacktrace

    - name: Upload Precompose Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: precompose-reports
        path: "precompose/build/reports/tests"

    - name: Upload Precompose ViewModel Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: precompose-viewmodel-reports
        path: "precompose-viewmodel/build/reports/tests"

    - name: Publishing
      if: startsWith(github.ref, 'refs/tags/')
      run: ./gradlew publish
